// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 05 Feb 2020 16:29:22 EET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package vulkan provides Go bindings for vulkan.h
*/
package vulkan
