// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 20 Oct 2019 22:36:59 NZDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package vulkan provides Go bindings for vulkan.h
*/
package vulkan
